name: Hosting dbt docs

on:
  push: main

jobs:
  hosting:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rye
        run: |
          curl -sSf https://rye-up.com/get | bash
      - name: Sync
        run: |
          rye sync
      - name: Activate
        run: |
          rye shell
      - name: Docs build
        run: |
          dbt docs generate

      - name: Copy files
        run: |
          mkdir docs && cp -r target/*.json target/index.html docs/

      - name: Deploy
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: dbt-docs
          directory: docs
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
